services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # UI de administraci√≥n
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - notification_network

  postgres:
    image: postgres:16-alpine
    container_name: postgres_notifications
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: parkin
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: db_notification
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - notification_network

networks:
  notification_network:
    driver: bridge

volumes:
  pgdata:
